---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Ubuntu"
  
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "Amazon Linux"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Amazon Linux"

  - name: add php support for apache
    yum:
      name: php
    when: ansible_distribution == "Amazon Linux"