---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php packages on Ubuntu
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages on Amazon linux
    yum:
      name:
      - httpd
      - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Amazon"
